name: bloom_filter
description: A bloom filter for Dart developers
version: 1.0.0
homepage: https://github.com/nielsenko/bloom_filter

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.0
