name: bloom_filter
description: A bloom filter for Dart developers
version: 1.0.0
homepage: https://github.com/nielsenko/bloom_filter

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  crypto: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
